### ISSUE TITLE
Key not present in Dictionary: 1

### ISSUE THREAD

**Issue by lucasholder** [kristijanhusak/vim-dadbod-completion#2]
I'm trying to use this as a coc extension. I have set `let g:db=...` , I also have `DATABASE_URL` set.

```viml
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" ...
Plug 'tpope/vim-dadbod'
" ...
call plug#end()

let g:db = $DATABASE_URL
```

The `:DB` command works fine (e.g. vim-dadbod is working). I am still not getting any autocompletion from this plugin and In `:CocOpenLog` I'm seeing those errors:

```
2020-04-25T11:17:03.332 ERROR (pid:56192) [completion-complete] - Complete error: db Error: request error nvim_call_function - Vim(let):E716: Key not present in Dictionary: 1
    at /Users/lucas/.config/nvim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/Users/lucas/.config/nvim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (/Users/lucas/.config/nvim/plugged/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/lucas/.config/nvim/plugged/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (/Users/lucas/.config/nvim/plugged/coc.nvim/build/index.js:12757:12)
2020-04-25T11:17:03.333 INFO (pid:56192) [completion-complete] - Results from: around
```

**Comment by lucasholder** [comment]
So the completion is working when I'm in a `:DBUI` buffer. But still getting errors when in a regular `.sql` file buffer.

**Comment by kristijanhusak** [comment]
Are you able to reproduce it 100% of time? What database type are you using?
Also, do you know if you have latest version installed?

**Comment by lucasholder** [comment]
Yep, always same error message. 
 Using `DATABASE_URL=postgres://postgres:changeme@localhost/accountant`. I just installed everything for the first time 30 minutes ago so should be using all latest versions.

**Comment by lucasholder** [comment]
`DATABASE_URL=postgres://postgres:changeme@localhost:5432/accountant` (with the explicit port) doesn't work either.

**Comment by kristijanhusak** [comment]
Can you please check if you get the error even before doing any autocompletion?
Just open up sql buffer, and then open CocLog to see if there's any error.

**Comment by lucasholder** [comment]
No errors if I don't start typing anything. Getting the error as soon as I start writing.

**Comment by kristijanhusak** [comment]
Ok, thanks. I'll look into it.

**Comment by lucasholder** [comment]
I should mention I'm using neovim `NVIM v0.4.0-2014-g554566cce`

**Comment by kristijanhusak** [comment]
I found an issue. Try opening some other file in vim, and they try to open your sql buffer. It should work.
This happens because caching is not properly triggered on vim enter event. I'm fixing it now. Just give that a test please.

**Comment by lucasholder** [comment]
That indeed worked! Thanks, I will wait for a fix.

**Comment by kristijanhusak** [comment]
I fixed it. Do a `:CocUpdate` and give it a test.

**Comment by lucasholder** [comment]
Thanks, that fixed the issue.
